# Configure the outgoing RabbitMQ exchange `mensaje-peticion`
mp.messaging.outgoing.mensaje-peticion.exchange.name=mensaje-peticion

# Configure the incoming RabbitMQ queue `mensaje-peticion`
mp.messaging.incoming.mensaje.queue.name=mensaje-peticion
mp.messaging.incoming.mensaje.exchange.name=mensaje-peticion

quarkus.rabbitmq.devservices.port=5672