# Configure the outgoing RabbitMQ exchange `mensaje-peticion`
mp.messaging.outgoing.mensaje-peticion.exchange.name=mensaje-peticion

# Configure the incoming RabbitMQ queue `mensaje-peticion`
mp.messaging.incoming.mensaje.queue.name=mensaje-peticion
mp.messaging.incoming.mensaje.exchange.name=mensaje-peticion

quarkus.rabbitmq.devservices.port=5672

#Mail
quarkus.mailer.from=jemirouseche@gmail.com    
quarkus.mailer.host=sandbox.smtp.mailtrap.io
quarkus.mailer.port=2525
quarkus.mailer.username=44a3033894d4ad
quarkus.mailer.password=****5ca7
quarkus.mailer.auth-methods=PLAIN
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.mock=false
quarkus.mailer.verify-host=false